### ISSUE TITLE
Fedora Install

### ISSUE THREAD

**Issue by ptrsmk** [zocker-160/keyboard-center#43] opened 2023-05-12 05:23 UTC
Would it be possible to get install instructions for Fedora, an AppImage, or an rpm package?  Thank you.

**Comment by zocker-160** [comment] 2023-05-12 12:17
Kinda duplicate of #39 and the second part of my answer https://github.com/zocker-160/keyboard-center/issues/39#issuecomment-1413545245 also applies to Fedora.

AppImage is sadly not an option as there is no way to guarantee that needed kernel modules are loaded and required udev rules are working (needs to place specific files into the host system and do a reboot) - none of this is possible with AppImage.

**Closed** 2023-05-14 13:48 UTC
Labels: wontfix
